export enum WORKSPACE_EVENT {
  MAP_RENAMED = 'MAP_RENAMED',
  MAP_DATA_UPDATED = 'MAP_DATA_UPDATED',
  MAP_DELETED = 'MAP_DELETED',
  TAB_UPDATED = 'TAB_UPDATED',
  SHARE_CREATED = 'SHARE_CREATED',
  SHARE_RECEIVED = 'SHARE_RECEIVED',
}
