export enum WORKSPACE_EVENT {
  RENAME_MAP = 'RENAME_MAP',
  UPDATE_MAP_DATA = 'UPDATE_MAP_DATA',
  DELETE_MAP = 'DELETE_MAP',
  UPDATE_TAB = 'UPDATE_TAB',
  CREATE_SHARE = 'CREATE_SHARE',
  ACCEPT_SHARE = 'ACCEPT_SHARE',
  WITHDRAW_SHARE = 'WITHDRAW_SHARE',
  REJECT_SHARE = 'REJECT_SHARE',
  MODIFY_SHARE_ACCESS = 'MODIFY_SHARE_ACCESS',
}
