export enum WORKSPACE_EVENT {
  MAP_RENAMED = 'MAP_RENAMED',
  MAP_DATA_UPDATED = 'MAP_DATA_UPDATED',
  MAP_DELETED = 'MAP_DELETED',
  TAB_UPDATED = 'TAB_UPDATED',
  SHARE_CREATED = 'SHARE_CREATED',
  SHARE_ACCEPTED = 'SHARE_ACCEPTED',
  SHARE_WITHDREW = 'SHARE_WITHDREW',
  SHARE_REJECTED = 'SHARE_REJECTED',
  SHARE_ACCESS_MODIFIED = 'SHARE_ACCESS_MODIFIED',
}
