import {sortNode} from "../selectors/MapSelector"
import {setIsTesting} from "../utils/Utils"
import {M, MPartial} from "../state/MapStateTypes"
import {mapDeInit} from "./MapDeInit"
import {mapInit} from "./MapInit"
import {mapReducerAtomic} from "./MapReducer"

const testFlow = (test: MPartial, result: MPartial, type: string, payload: object) => {
  mapInit(test)
  mapReducerAtomic(test as M, type, payload)
  return expect(mapDeInit(test as M).sort(sortNode)).toEqual((result as M).sort(sortNode))
}

describe("Move_tests", () => {
  // @ts-ignore
  beforeEach(() => setIsTesting())

  test('duplicateR', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['l', 0], fromNodeId: 'b', toNodeId: 'e'},
    {nodeId: 'c', path: ['l', 1], fromNodeId: 'b', toNodeId: 'h'},
    {nodeId: 'd', path: ['l', 2], fromNodeId: 'b', toNodeId: 'k'},
    {nodeId: 'e', path: ['l', 3], fromNodeId: 'h', toNodeId: 'k'},
    {nodeId: 'i', path: ['r', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'l', path: ['r', 2], selected: 1},
    {nodeId: 'm', path: ['r', 2, 'd', 0]},
    {nodeId: 'n', path: ['r', 2, 'd', 0, 's', 0]},
    {nodeId: 'o', path: ['r', 3], selected: 2},
    {nodeId: 'p', path: ['r', 3, 'd', 0]},
    {nodeId: 'q', path: ['r', 3, 'd', 0, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    // {nodeId: 'b', path: ['l', 0], fromNodeId: 'b', toNodeId: 'e'},
    // {nodeId: 'c', path: ['l', 1], fromNodeId: 'b', toNodeId: 'h'},
    // {nodeId: 'd', path: ['l', 2], fromNodeId: 'b', toNodeId: 'k'},
    // {nodeId: 'e', path: ['l', 3], fromNodeId: 'h', toNodeId: 'k'},
    // {nodeId: 'f', path: ['l', 4], fromNodeId: 'b', toNodeId: 'u'},
    // {nodeId: 'g', path: ['l', 5], fromNodeId: 'b', toNodeId: 'x'},
    // {nodeId: 'h', path: ['l', 6], fromNodeId: 'u', toNodeId: 'x'},
    {nodeId: 'i', path: ['r', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'l', path: ['r', 2]},
    {nodeId: 'm', path: ['r', 2, 'd', 0]},
    {nodeId: 'n', path: ['r', 2, 'd', 0, 's', 0]},
    {nodeId: 'o', path: ['r', 3]},
    {nodeId: 'p', path: ['r', 3, 'd', 0]},
    {nodeId: 'q', path: ['r', 3, 'd', 0, 's', 0]},
    {nodeId: 'u', path: ['r', 4], selected: 1},
    {nodeId: 'v', path: ['r', 4, 'd', 0]},
    {nodeId: 'w', path: ['r', 4, 'd', 0, 's', 0]},
    {nodeId: 'x', path: ['r', 5], selected: 2},
    {nodeId: 'y', path: ['r', 5, 'd', 0]},
    {nodeId: 'z', path: ['r', 5, 'd', 0, 's', 0]},
  ] as MPartial, 'duplicateR', {}))

  test('duplicateS', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 1], selected: 1},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 2], selected: 2},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 3]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 2]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'u', path: ['r', 0, 'd', 0, 's', 3], selected: 1},
    {nodeId: 'v', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'w', path: ['r', 0, 'd', 0, 's', 4], selected: 2},
    {nodeId: 'x', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 5]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 5, 's', 0]},
  ] as MPartial, 'duplicateS', {}))

  test('moveSD', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 1], selected: 1},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 2], selected: 2},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 3]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 4]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 1]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 2], selected: 1},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 3], selected: 2},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 4]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial, 'moveSD', {}))

  test('moveST', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 2]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 3], selected: 1},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 4], selected: 2},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0], selected: 1},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 1], selected: 2},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 2]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 3]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 4]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial,'moveST', {}))

  test('moveSU', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 2], selected: 1},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 3], selected: 2},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 4]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 1], selected: 1},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 2], selected: 2},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 3]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 4]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial,'moveSU', {}))

  test('moveSB', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0], selected: 1},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 1], selected: 2},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 2]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 3]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 4]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 1]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 2]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 3], selected: 1},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 4], selected: 2},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 4, 's', 0]},
  ] as MPartial,'moveSB', {}))

  test('moveSO', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 's', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1], selected: 1},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 1, 's', 1]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 2], selected: 2},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 2, 's', 1]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 's', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 's', 2], selected: 1},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 's', 2, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 's', 2, 's', 1]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 's', 3], selected: 2},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 's', 3, 's', 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 's', 3, 's', 1]},
  ] as MPartial,'moveSO', {}))

  test('moveSI', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 's', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 's', 2], selected: 1},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 's', 3], selected: 2},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 's', 3, 's', 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 's', 4]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 1]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 1, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 's', 1]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 's', 2]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1], selected: 1},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 2], selected: 2},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 2, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 3]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 3, 's', 0]},
  ] as MPartial,'moveSI', {}))

  test('moveSIR', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 1], selected: 1},
    {nodeId: 'f', path: ['r', 0, 'd', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 1, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 1, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 1, 's', 1], selected: 1},
  ] as MPartial, 'moveSIR', {}))

  test('moveSIL', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 1]},
    {nodeId: 'f', path: ['r', 0, 'd', 1, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 1, 's', 1], selected: 1},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 1], selected: 1},
    {nodeId: 'e', path: ['r', 0, 'd', 1]},
    {nodeId: 'f', path: ['r', 0, 'd', 1, 's', 0]},
  ] as MPartial, 'moveSIL', {}))

  test('moveCRD', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0], selected: 1},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1], selected: 2},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0], selected: 1},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1], selected: 2},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, 'moveCRD', {}))

  test('moveCRU', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0], selected: 1},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1], selected: 2},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0], selected: 1},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1], selected: 2},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, 'moveCRU', {}))

  test('moveCCR', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0], selected: 1},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0], selected: 2},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1], selected: 1},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1], selected: 2},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, 'moveCCR', {}))

  test('moveCCL', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1], selected: 1},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1], selected: 2},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0], selected: 1},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0], selected: 2},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
  ] as MPartial, 'moveCCL', {}))

  test('moveS2TOR', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0], selected: 1},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 1]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 2]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 't', path: ['r', 0, 'd', 0, 's', 0], selected: 1},
    {nodeId: 'u', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'v', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'w', path: ['r', 0, 'd', 0, 's', 0, 'c', 2, 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 2, 0, 's', 0]},
  ] as MPartial, 'moveS2TOR', {}))

  test('moveS2TO', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0], selected: 1, selection: 'f'},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 's', 1]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 's', 2]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0]},
    {nodeId: 't', path: ['r', 0, 'd', 0, 's', 0, 's', 0], selected: 1},
    {nodeId: 'u', path: ['r', 0, 'd', 0, 's', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'v', path: ['r', 0, 'd', 0, 's', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'w', path: ['r', 0, 'd', 0, 's', 0, 's', 0, 'c', 2, 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 's', 0, 'c', 2, 0, 's', 0]},
  ] as MPartial, 'moveS2TO', {}))

  test('transpose', () => testFlow([
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0], selected: 1},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 2]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 2, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1]},
    {nodeId: 'n', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
    {nodeId: 'o', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 2]},
    {nodeId: 'p', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 2, 's', 0]},
  ] as MPartial, [
    {nodeId: 'a', path: ['g']},
    {nodeId: 'b', path: ['r', 0]},
    {nodeId: 'c', path: ['r', 0, 'd', 0]},
    {nodeId: 'd', path: ['r', 0, 'd', 0, 's', 0], selected: 1},
    {nodeId: 'e', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0]},
    {nodeId: 'f', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 0, 's', 0]},
    {nodeId: 'k', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1]},
    {nodeId: 'l', path: ['r', 0, 'd', 0, 's', 0, 'c', 0, 1, 's', 0]},
    {nodeId: 'g', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0]},
    {nodeId: 'h', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 0, 's', 0]},
    {nodeId: 'm', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1]},
    {nodeId: 'n', path: ['r', 0, 'd', 0, 's', 0, 'c', 1, 1, 's', 0]},
    {nodeId: 'i', path: ['r', 0, 'd', 0, 's', 0, 'c', 2, 0]},
    {nodeId: 'j', path: ['r', 0, 'd', 0, 's', 0, 'c', 2, 0, 's', 0]},
    {nodeId: 'o', path: ['r', 0, 'd', 0, 's', 0, 'c', 2, 1]},
    {nodeId: 'p', path: ['r', 0, 'd', 0, 's', 0, 'c', 2, 1, 's', 0]},
  ] as MPartial, 'transpose', {}))
})
