export enum MR {
  load = 'load',

  undo = 'undo',
  redo = 'redo',
  saveView = 'saveView',
  saveFromCoordinates = 'saveFromCoordinates',
  startEditReplace = 'startEditReplace',
  startEditAppend = 'startEditAppend',
  removeMapListEntriesOfEdit = 'removeMapListEntriesOfEdit',

  setDensitySmall = 'setDensitySmall',
  setDensityLarge = 'setDensityLarge',
  setPlaceTypeExploded = 'setPlaceTypeExploded',
  setPlaceTypeIndented = 'setPlaceTypeIndented',

  selectR = 'selectR',
  selectS = 'selectS',
  selectC = 'selectC',
  selectFirstR = 'selectFirstR',
  selectFirstS = 'selectFirstS',
  selectFirstC = 'selectFirstC',
  selectFirstCR = 'selectFirstCR',
  selectFirstCC = 'selectFirstCC',
  selectSelfX = 'selectSelfX',
  selectFamilyX = 'selectFamilyX',
  selectSD = 'selectSD',
  selectSU = 'selectSU',
  selectRSO = 'selectRSO',
  selectSSO = 'selectSSO',
  selectSSOLast = 'selectSSOLast',
  selectCSO = 'selectCSO',
  selectSI = 'selectSI',
  selectLCS = 'selectLCS',
  selectRCS = 'selectRCS',
  selectDCS = 'selectDCS',
  selectUCS = 'selectUCS',
  selectCFR0 = 'selectCFR0',
  selectCFC0 = 'selectCFC0',
  selectCFF = 'selectCFF',
  selectXSIR = 'selectXSIR',
  selectXSIRS = 'selectXSIRS',
  selectXSIC = 'selectXSIC',
  selectXSICS = 'selectXSICS',
  selectXCIS = 'selectXCIS',
  selectAddR = 'selectAddR',
  selectAddS = 'selectAddS',
  selectAddSD = 'selectAddSD',
  selectAddSU = 'selectAddSU',
  selectRA = 'selectRA',
  selectSA = 'selectSA',
  selectSameCR = 'selectSameCR',
  selectSameCC = 'selectSameCC',
  selectCD = 'selectCD',
  selectCU = 'selectCU',
  selectCR = 'selectCR',
  selectCL = 'selectCL',
  selectSByRectanglePreview = 'selectSByRectanglePreview',
  selectSByRectangle = 'selectSByRectangle',

  unselect = 'unselect',
  unselectR = 'unselectR',
  unselectS = 'unselectS',
  unselectC = 'unselectC',

  insertL = 'insertL',
  insertR = 'insertR',
  insertSD = 'insertSD',
  insertSU = 'insertSU',
  insertRSO = 'insertRSO',
  insertSSO = 'insertSSO',
  insertCSO = 'insertCSO',
  insertSOText = 'insertSOText',
  insertSOLink = 'insertSOLink',
  insertSOImage = 'insertSOImage',
  insertCRD = 'insertCRD',
  insertCRU = 'insertCRU',
  insertSCRD = 'insertSCRD',
  insertSCRU = 'insertSCRU',
  insertCCR = 'insertCCR',
  insertCCL = 'insertCCL',
  insertSCCR = 'insertSCCR',
  insertSCCL = 'insertSCCL',
  insertSUTable = 'insertSUTable',
  insertSDTable = 'insertSDTable',
  insertSOTable = 'insertSOTable',

  gptParseNodesS = 'gptParseNodesS',
  gptParseNodesT = 'gptParseNodesT',
  gptParseNodeMermaid = 'gptParseNodeMermaid',

  deleteL = 'deleteL',
  deleteLR = 'deleteLR',
  deleteSJumpSU = 'deleteSJumpSU',
  deleteSJumpSD = 'deleteSJumpSD',
  deleteSJumpSI = 'deleteSJumpSI',
  deleteSJumpR = 'deleteSJumpR',
  deleteCRJumpU = 'deleteCRJumpU',
  deleteCRJumpD = 'deleteCRJumpD',
  deleteCRJumpSI = 'deleteCRJumpSI',
  deleteCCJumpL = 'deleteCCJumpL',
  deleteCCJumpR = 'deleteCCJumpR',
  deleteCCJumpSI = 'deleteCCJumpSI',

  cutLR = 'cutLR',
  cutSJumpRI = 'cutSJumpRI',
  cutSJumpSU = 'cutSJumpSU',
  cutSJumpSD = 'cutSJumpSD',
  cutSJumpSI = 'cutSJumpSI',
  cutSJumpCI = 'cutSJumpCI',

  copyLR = 'copyLR',
  copyS = 'copyS',

  pasteLR = 'pasteLR',
  pasteSO = 'pasteSO',

  duplicateR = 'duplicateR',
  duplicateS = 'duplicateS',

  moveSD = 'moveSD',
  moveST = 'moveST',
  moveSU = 'moveSU',
  moveSB = 'moveSB',
  moveSO = 'moveSO',
  moveSI = 'moveSI',
  moveSByDragPreview = 'moveSByDragPreview',
  moveSByDrag = 'moveSByDrag',
  moveCRD = 'moveCRD',
  moveCRU = 'moveCRU',
  moveCCR = 'moveCCR',
  moveCCL = 'moveCCL',
  moveS2T = 'moveS2T',

  transpose = 'transpose',

  offsetD = 'offsetD',
  offsetU = 'offsetU',
  offsetR = 'offsetR',
  offsetL = 'offsetL',
  offsetRByDragPreview = 'offsetRByDragPreview',
  offsetRByDrag = 'offsetRByDrag',

  setControlTypeNone = 'setControlTypeNone',
  setControlTypeIngestion = 'setControlTypeIngestion',
  setControlTypeExtraction = 'setControlTypeExtraction',

  setContentText = 'setContentText',
  setContentEquation = 'setContentEquation',
  setContentMermaid = 'setContentMermaid',

  setLineWidth = 'setLineWidth',
  setLineType = 'setLineType',
  setLineColor = 'setLineColor',
  setSBorderWidth = 'setSBorderWidth',
  setFBorderWidth = 'setFBorderWidth',
  setSBorderColor = 'setSBorderColor',
  setFBorderColor = 'setFBorderColor',
  setSFillColor = 'setSFillColor',
  setFFillColor = 'setFFillColor',
  setTextFontSize = 'setTextFontSize',
  setTextColor = 'setTextColor',
  setBlur = 'setBlur',

  setTaskModeOn = 'setTaskModeOn',
  setTaskModeOff = 'setTaskModeOff',
  setTaskModeReset = 'setTaskModeReset',
  setTaskStatus = 'setTaskStatus',

  clearDimensions = 'clearDimensions',
  clearLine = 'clearLine',
  clearSBorder = 'clearSBorder',
  clearFBorder = 'clearFBorder',
  clearSFill = 'clearSFill',
  clearFFill = 'clearFFill',
  clearText = 'clearText',
  clearBlur = 'clearBlur',
}
