export let selectionState = {
    structSelectedPathList: [],
    cellSelectedPathList: [],
    maxSel: 0,
    scope: '',
    lastPath: [],
    geomHighPath: [],
    geomLowPath: [],
    cellRowSelected: 0,
    cellRow: 0,
    cellColSelected: 0,
    cellCol: 0,
    haveSameParent: 0,
    sameParentPath: [],
}
